Update setup_image

diff --git a/.github/workflows/setup_image b/.github/workflows/setup_image
--- a/.github/workflows/setup_image
+++ b/.github/workflows/setup_image
@@ -1,6 +1,6 @@
 #!/bin/bash
 set -uo pipefail
-trap 's=$?; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
+trap 's=${?:-}; echo "$0: Error on line "$LINENO": $BASH_COMMAND"; exit $s' ERR
 IFS=$'\n\t'
 
 # Source for this script:
@@ -37,7 +37,7 @@ else
     echo "gpu_mem=${GPU_MEM}" >> /boot/config.txt
 fi
 
-grep "gpu_mem" < /boot/config.txt | ..
+grep "gpu_mem" < /boot/config.txt
 
 echo "Setting hostname."
 sed -i "s/raspberrypi/pi-zero-w/" /etc/hostname
